#!/usr/bin/env bash

dreamsdk_release=$(dreamsdk-get-info --release)
dreamsdk_date=$(dreamsdk-get-info --date)

# Display DreamSDK welcome messages
if [ ${kos_initialized} -eq 0 ]; then
  echo "KallistiOS is not installed."
  echo "Please run DreamSDK Manager to set-up everything."
  echo "Enter dreamsdk-manager at the command prompt to do that."
else
  echo "   ___                     _______  __ __";
  echo "  / _ \_______ ___ ___ _  / __/ _ \/ //_/";
  echo " / // / __/ -_) _ \`/  ' \_\ \/ // /  ,<   ";
  echo "/____/_/  \__/\_,_/_/_/_/___/____/_/|_|  ";
  echo "                                         ";
  echo "DreamSDK ${dreamsdk_release} - Built on ${dreamsdk_date}"
fi
