#!/usr/bin/env bash

me=`basename "$0"`
  
source=$1
destination=$2

if [ -z "$source" ]; then
  echo "usage: $me <binary.elf> [binary.bin]";
  exit 1
fi

if [ ! -f "$source" ]; then
  echo "$me: error: file not found: $source";
  exit 2
fi

if [ -z "$destination" ]; then
  destination="${source%.*}.bin"
fi

tmpfile="/tmp/$(basename $0).$$.tmp"

cp $source $tmpfile
kos-strip $tmpfile
kos-objcopy -O binary $tmpfile $destination
rm $tmpfile
