#!/usr/bin/env bash

if [ -z "$toolchains_base" ]; then
  echo "fatal: \$toolchain_base is undefined!";
  exit;
fi

kos_ports_base=$toolchains_base/kos-ports
example_dir=${kos_ports_base}/examples
include_dir=${kos_ports_base}/include
lib_dir=${kos_ports_base}/lib

if [ -d ${example_dir} ]; then
  rm -rf ${example_dir} 
fi

if [ -d ${include_dir} ]; then
  rm -rf ${include_dir}
fi

if [ -d ${lib_dir} ]; then
  rm -rf ${lib_dir}
fi
