#!/usr/bin/env bash

if [ -z "${DREAMSDK_BASE_TOOLCHAINS}" ]; then
  echo "fatal: \$DREAMSDK_BASE_TOOLCHAINS is undefined!";
  exit;
fi

# Get dc-tool parameters
kind=$(awk -F "=" '/Kind/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})
executable=$(awk -F "=" '/Executable/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})
commandline=$(awk -F "=" '/CommandLine/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})
dreamcast_ip=$(awk -F "=" '/InternetProtocolAddress/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})
dreamcast_mac=$(awk -F "=" '/MediaAccessControlAddress/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})
host_mac=$(awk -F "=" '/HostMediaAccessControlAddress/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})
use_arp=$(awk -F "=" '/MediaAccessControlEnabled/ {print $2;}' ${DREAMSDK_CFG_DCTOOL})

dreamcast_tool_not_configured() {
  echo "Dreamcast Tool (dc-tool) is not configured."
  echo "Please run DreamSDK Manager to do the configuration."
  echo "You may type \"dreamsdk manage\" to do that."  
  exit 1
}

# check the executable presence and the good configuration
is_executable_exists=$(command -v $executable)
if [ "$kind" == "0" ] || [ -z "$is_executable_exists" ]; then
  dreamcast_tool_not_configured
fi

# Handle arp
if [ "$kind" == "2" ] && [ "$use_arp" == "1" ]; then
  fastping ${dreamcast_ip}
  if [ $? -ne 0 ]; then
    is_uac_enabled=$(uac-status)
    if [ "$is_uac_enabled" == "1" ]; then    
      echo "Please confirm UAC to allow the ARP entry addition..."
    fi
	fastarp ${host_mac} ${dreamcast_ip} ${dreamcast_mac}
  fi
fi

# Handle user params

# Thanks: https://stackoverflow.com/a/1683850/3726096
trim()
{
    local trimmed="$1"

    # Strip leading spaces.
    while [[ $trimmed == ' '* ]]; do
       trimmed="${trimmed## }"
    done
    # Strip trailing spaces.
    while [[ $trimmed == *' ' ]]; do
        trimmed="${trimmed%% }"
    done

    echo "$trimmed"
}

# Thanks: https://stackoverflow.com/a/1669493/3726096
userparams=""
whitespace="[[:space:]]"
for i in "$@"
do
    if [[ $i =~ $whitespace ]]
    then
        i=\"$i\"
    fi
    userparams+="$i "
done

# run the loader!
dctool_cmd="${executable} ${commandline} $(trim "${userparams}")"
bash -c "${dctool_cmd}"
