#!/usr/bin/env bash

source=$1
destination=$2

if [ -z "$source" ]; then
  me=`basename "$0"`
  echo "usage: $me <binary.elf> [binary.bin]";
  exit 1
fi

if [ -z "$destination" ]; then
  destination="${source%.*}.bin"
fi

kos-objcopy -O binary $source $destination
