#!/usr/bin/env bash

if [ -z "$toolchains_base" ]; then
  echo "fatal: \$toolchain_base is undefined!";
  exit;
fi

dreamcast_tool_kind=$(awk -F "=" '/DreamcastToolKind/ {print $2}' ${dreamsdk_conf})

dreamcast_tool_not_configured() {
  printf "Dreamcast Tool (dc-tool) is not configured.\n"
  printf "Please run the DreamSDK Manager utility to set it up.\n"
  exit 1
}

dreamcast_tool=
case ${dreamcast_tool_kind} in
  0) dreamcast_tool_not_configured;; 
  1) dreamcast_tool="dc-tool-ser";;
  2) dreamcast_tool="dc-tool-ip";;
  *) dreamcast_tool_not_configured;;
esac

${dreamcast_tool} $*
