#!/usr/bin/env bash

if [ -z "$toolchains_base" ]; then
  echo "fatal: \$toolchain_base is undefined!";
  exit;
fi

# Get the right dc-tool executable
dreamcast_tool_kind=$(awk -F "=" '/Kind/ {print $2}' ${dreamsdk_conf})

dreamcast_tool_not_configured() {
  echo "Dreamcast Tool (dc-tool) is not configured."
  echo "Please run the DreamSDK Manager utility to set it up."
  echo "Enter dreamsdk-manager at the command prompt to do that."  
  exit 1
}

# Parameters are filled by DreamSDK Manager
# Don't manually modify this!
dreamcast_tool_parameters="-t COM2 -b 115200 -n -q"

# Get the dc-tool executable filename to use
dreamcast_tool=""
case ${dreamcast_tool_kind} in
  0) dreamcast_tool_not_configured;; 
  1) dreamcast_tool="dc-tool-ser";;
  2) dreamcast_tool="dc-tool-ip";;
  *) dreamcast_tool_not_configured;;
esac

${dreamcast_tool} ${dreamcast_tool_parameters} $*
