#!/usr/bin/env bash

if [ -z "$dreamsdk_base" ]; then
  echo "fatal: \$dreamsdk_base is undefined!";
  exit;
fi

dreamsdk_version_file=${dreamsdk_base}/VERSION
dreamsdk_release=$(awk -F "=" '/Release/ {print $2}' ${dreamsdk_version_file})
dreamsdk_date=$(awk -F "=" '/Date/ {print $2}' ${dreamsdk_version_file})

# Display DreamSDK welcome messages
if [ ${kos_initialized} -eq 0 ]; then
  echo "KallistiOS is not installed."
  echo "Please run DreamSDK Manager to set-up everything."
  echo "Enter dreamsdk-manager at the command prompt to do that."
else
  echo "   ___                     _______  __ __";
  echo "  / _ \_______ ___ ___ _  / __/ _ \/ //_/";
  echo " / // / __/ -_) _ \`/  ' \_\ \/ // /  ,<   ";
  echo "/____/_/  \__/\_,_/_/_/_/___/____/_/|_|  ";
  echo "                                         ";
  echo "DreamSDK Release ${dreamsdk_release} - Built on ${dreamsdk_date}"
fi
