#!/usr/bin/env bash

if [ -z "$WINAPP" ]; then
  echo "fatal: \$WINAPP is undefined!";
  exit 1;
fi

WINROOTDIR=$(cd / && pwd -W)

PARAMS=()
for i in "$@"
do
	if [[ -f "${i}" ]] || [[ -d "${i}" ]]
	then
	  PARAMS+=("${WINROOTDIR}${i}")
	else
	  PARAMS+=("${i}")
	fi
done

WINPARAMS=""
first=1
for value in "${PARAMS[@]}"
do
	 if [[ ${first} -eq 0 ]]
	 then
	   WINPARAMS+=" "
	 fi
	 first=0
	 WINPARAMS+="\"${value//\$/\\$}\""	 
done

MSYS_NO_PATHCONV=1 bash -c "${WINAPP} ${WINPARAMS}"
