#!/usr/bin/env bash

dreamsdk_release=$(dreamsdk-get-info --release 2>/dev/null) || dreamsdk_release="(Unknown Release)"
dreamsdk_build=$(dreamsdk-get-info --build)
dreamsdk_date=$(dreamsdk-get-info --date)

kosports_status_installed=$(kosports status installed)
kosports_status_available=$(kosports status available)

echo " ____                         _____  ____   _____ ";
echo "|    .  ___  ___  ___  _____ |   __||    . |  |  |";
echo "|  |  ||  _|| -_|| .'||     ||__   ||  |  ||    -|";
echo "|____/ |_|  |___||__,||_|_|_||_____||____/ |__|__|";
echo "                                                  ";
echo -e "\033[1;30;1;47mDreamSDK ${dreamsdk_release} (${dreamsdk_build})\033[0m - Built on ${dreamsdk_date}";
echo "${kosports_status_installed} KallistiOS Ports installed out of ${kosports_status_available} available";
echo "";
echo "Run \"dreamsdk\" for help with commands and usage.";

if [ "${DREAMSDK_KOS_INITIALIZED:-0}" -eq 0 ]; then
  echo "";
  echo -e "\033[1;33;1;41m*** WARNING: KallistiOS is not properly installed/initialized ***\033[0m"; 
  echo "Please run \"dreamsdk manage\" to fix the issue.";
fi

unset dreamsdk_release
unset dreamsdk_build
unset dreamsdk_date
unset kosports_status_installed
unset kosports_status_available
